#!/bin/bash
# set -euo pipefail
set -x
URL=${URL:-http://jodel-app.com}

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

rm -rf /tmp/*

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

dropbear -E -F &
DB_PID=$!

Xorg &
X_PID=$!

echo "Waiting for X to be ready"
export DISPLAY=:0

# Setting wallpaper and polling X in one!
while ! feh --bg-scale /etc/wallpaper.png; do sleep 1; done
matchbox-window-manager -use_cursor no &

while ! curl -sf -o /dev/null "$URL"; do sleep 1; done

xset -dpms
xset s off
xset s noblank

su -c "chromium-browser --incognito --kiosk $URL" chromium

sleep infinity

